# Acknowledgements {-}

Before we proceed further with the contents in the lab manual, we would like to acknowledge the following people who contributed to elaboration and maintenance of this RIPLRT Lab Manual:

- **Past Members of the RIPLRT**: Ariel Stateman, Shandra Bellinger, Hayat Srour, Ruslan Fomenko, Summer Pellechio, Sukeina Nasser and Josh Baguley, who contributed heavily to the initial steps of the RIPLRT Lab Manual.
- **Current Members of the RIPLRT**: Thanks to the current members of the RIPLRT (https://www.riplrt.com/members) who are contributing update iterations of the RIPLRT Lab Manual.
- The [AlyLab](https://www.alylab.org/) for sharing, in a recent publication [@alylab2018] in [Nature News and Comments](https://www.nature.com/articles/d41586-018-06167-w), the idea and benefits of having a lab manual. 
- My writing group within the University of Arizona [PRIDE-AIRE 2019 program](https://diversity.uahs.arizona.edu/advanced-respiratory-research-equity-aire-az-pride-program), Drs. [Maria Coutinho](https://vivo.brown.edu/display/mcoutinh) and [Mariam BA](https://www.researchgate.net/profile/Mariam_Ba) from Brown University and University of Nevada-Reno, respectively; and our writing mentor [Dr. Karen Barto](https://cesl.arizona.edu/people/barto-karen), from the University of Arizona, for their contribution in revising sections of this lab manual.  


Now, let’s get back to the lab manual!

