# Expectations and Responsabilities 

The core values of the RIPLRT are 

- Inclusiveness (everyone’s voice counts)
- Multi-disciplinary focus (integrate different disciplines into our research goals)
- Diversity (value and respect differences in perspectives and opinions)
- Integrity (follow strict institutional, scientific, and ethical guidelines)
- Productivity (input our highest efforts to reach our goals)
- Innovation (remain open-minded, and will learn from both successes and failures)
- Excellence (target the highest quality of scientific research)
- Collaboration (what is done in isolation is often accomplished better in partnership)
- Leadership (nourish from a culture of intra and inter-motivation and inspiration)

We feel that these values are vital to success in science, and it is important that every member of the RIPL_Effect Research Team strive to fulfill them at all times.

It is also important to maintain a healthy work environment. Any petty actions or drama that hinder our efforts  - we do not have room for petty actions or drama in the RIPL_Effect Research Team. 

## General Expectations and Responsabilities 
It is expected that every member 

- Maintain a passion for science that carries you forward. Science is very rewarding, but also very challenging. By keeping your scientific goals in mind, it is possible to stay motivated in the challenging times.
- Be efficient but do not rush. Rushing leads to mistakes and inconveniences further down the line. It is important to always know exactly what you are doing before you do it. Plan out experiments ahead of time and, like you have learned in the BCA assay (which everyone in RIPLRT has to go through), always be prepared.
- Learn from mistakes because mistakes do happen -- they can be corrected, but only if you own up to them. Never hide a mistake as that will lead to future problems down the line. 
- Never be too proud to ask for help. We are not competing with each other, we are a team and will help each other whenever possible. Pride is good, but too much pride is unhealthy.
- Maintain a respectful atmosphere with your lab members. Recall that one of our core values is diversity, and for this reason we must be able to recognize and work with the diverse environment we will encounter in and outside the lab as we carry out our scientific duties. 
- Learn to employ your [emotional intelligence](https://en.wikipedia.org/wiki/Emotional_intelligence) with your lab members: this is an important skill set very often underestimate in society. Be thoughtful about if your action(s) will hinder the emotions of the person you are about to interact with.  
- Employ intelligence and respect when addressing conflicts within the RIPLRT. As with any relationship, conflicts may arise -- we have to deliver the same or higher level of intelligence and respect (a.k.a. diplomacy) as we do with science to resolve conflicts. 
- Keep up with science as much as possible. [Twitter](https://lternet.edu/twitter-for-scientists/) is a good platform to do so; therefore, it is highly recommended to have a Twitter account. Also refer to Lab Resources (chapter 3) to learn about PubCrawler. 
- Learn and employ time management. Working everyday in RIPLRT is not necessary, and it is not the same as getting the work done. Just make sure to dedicate the time needed to get the work completed. 
- Attend meetings as they are in hard date/time schedules, and be on time with regards to your duties in RIPLRT. Lab members will always be grateful when we respect their time: you want them to respect yours. 
- Before leaving the lab, make sure our working spaces are clean and organized, and that lab equipments (except for the freezer, fridge, and computers) is turned off. 
- Share the space. The RIPLRT research facilities are within a shared research lab. There are things that can be shared, and there are things that cannot. Make sure to recognize how items falls into these two categories. 
- Work honestly. Never plagiarize work, tamper with data, or omit anything. A “bad” result is still a result: negative results also have the potential to be published. This seems an appropriate time to mention that most of these expectations stem from the [Aly Lab Manual](https://github.com/alylab/labmanual)(1).  

## Principle Investigator
All general expectations and responsibilities and 

- Be the foundation and example for the lab members to follow
- Be a mentor with many aspects within RIPLRT, including science, learning, personally, emotionally, with career goals, among others. 
- Provide feedback to in a timely manner, as much as possible, in all scientific aspects of RIPLRT
- Facilitate as many scientific and learning opportunities as possible for lab members to benefit from 
- Find and apply for funding, and identify collaborative opportunities 
- Have our backs as long as we have implemented the guidelines in Lab Manual. Also, be as impartial as possible in this manner. 
- In order to back up us, the Principal Investigator will perform monthly of the riplrt.com domain as well as with the different workspaces and platforms employed by RIPLRT.

## Lab Manager
All general expectations and responsabilities and

- Assist the Principal Investigator in the management of the research team
- Assist in the ordering of equipments, reagents, and other lab consumables
- Manage, develop, and implement strategies for inventory control
- Assist in the preparation of agendas for the weekly meetings and extraordinary meeting
- Serve as mentors for research assistants, graduate and undergraduate students, or other interns
- Elaborate questions that the group can use to develop new research ideas
- Assist in any projects in which mentees may need help with, as well as with the Principal Investigator
- Participate, as much as possible, in professional development opportunities including those identified by the Principal Investigator as well as those identified by yourself
- Be willing to learn how to improve written and verbal communication as it pertains to the scientific community

## Research Assistants
All general expectations and responsibilities and 

- Serve as mentors for graduate and undergraduate students, or other interns
- Train lesser experienced lab members on lab techniques and protocols, including guidelines of this lab manual
- Elaborate questions that the group can use to develop new research ideas
- Assist in any projects in which mentees and mentors may need help with, as well as with the Principal Investigator
- Participate, as much as possible, in professional development opportunities including those identified by the Principal Investigator as well as those identified by yourself
- Be willing to learn how to improve written and verbal communication as it pertains to the scientific community

## Graduate Students
All general expectations and responsibilities and 

- Be mentees of research assistants 
- Mentor lesser experiences lab members
- Learn new skills and procedures quickly
- Elaborate questions that the group can use to develop new research ideas
- Assist in any projects in which mentees and mentors may need help with, as well as with the Principal Investigator
- Participate, as much as possible, of professional development opportunities including those identified by the Principal Investigator as well as those identified by yourself
- Be willing to learn how to improve written and verbal communication in science

## Undergraduate interns
All general expectations and responsibilities and 

- Be mentees of research assistants and graduate students 
- Learn new skills and procedures quickly
- Assist in any projects in which mentors may need help with, as well as with the Principal Investigator
- Participate, as much as possible, of professional development opportunities including those identified by the Principal Investigator as well as those identified by yourself
- Be willing to learn how to improve written and verbal communication in science
