# Vision, Mission, and Core Values

## Vision
To provide further insight into the immuno-physiological health effects that airborne pollutants of different chemical origins induce once they cross the human respiratory barrier among susceptible individuals such as people suffering from asthma, respiratory allergies, and other chronic respiratory conditions). We also seek to foster an environment that leads to enrichment in the professional, personal, and academic aspects of the RIPLRT members and interns. 

## Mission
We seek to address our scientific questions by integrating human-based immuno-physiological approaches, molecular biology, and computational biology. Also, we will identify opportunities to collaborate, employ and enhance our expertise in respiratory health, immunology, and data analytics.  Lastly, implementing our Core Values, for example inclusiveness, inclusiveness, diversity, and integrity will be essential in following upon our Vision and Mission. 

## Core Values
The core values of the RIPLRT are 

- Inclusiveness (everyone’s voice counts)
- Multi-disciplinary focus (integrate different disciplines into our research goals)
- Diversity (value and respect differences in perspectives and opinions)
- Integrity (follow strict institutional, scientific, and ethical guidelines)
- Productivity (input our highest efforts to reach our goals)
- Innovation (remain open-minded, and learn from both successes and failures)
- Excellence (target the highest quality of scientific research)
- Collaboration (what is done in isolation is often accomplished better in partnership)
- Leadership (nourish from a culture of intra and inter-motivation and inspiration)

We feel that these Core Values are vital to success in science, and it is important that every member of the RIPLRT strive to fulfill them at all times.

It is also important to maintain a healthy work environment. *Professionalism* must always be implemented to maintain, and refrain from unnecessary or inappropriate commentary: this will greatly contribute to a healthy RIPLRT environment. 