# Expectations and Responsibilities 

## General Expectations and Responsibilities 
It is expected that each member of the RIPLRT... 

- **will maintain a passion for science and projects for which he/she is involved**. Science is very rewarding, but also very challenging -- keep your scientific goals in mind, and stay motivated.
- **will be efficient but not rushing**. Rushing leads to mistakes and inconveniences further down the line, such as having to repeat experiments and consuming valuable resources. Thus, it is important to know exactly what we are doing before we do it. Plan out and familiarize with experiments, as well as projects. Also, being prepared ahead of time helps in identifying necessary troubleshooting.
- **will learn from mistakes because mistakes do happen**. Keep in mind that mistakes can be corrected **only** if we own up to them. Never hide from a mistake because it will lead to future problems, and may jeopardize our stay in the RIPLRT.
- **will not be too proud to ask for help**. We are a team and will help each other whenever possible. *Pride is good, but too much pride is unhealthy*.
- **will maintain a respectful atmosphere with lab-mates**. Diversity is one of our [Core Value](https://bookdown.org/friveram/labmanualriplrt/vision-mission-and-core-values.html#vision); we must recognize and work with the diverse environment we will encounter in and outside the RIPLRT. 
- **will employ [emotional intelligence](https://en.wikipedia.org/wiki/Emotional_intelligence) and diplomacy**. Be thoughtful if your action(s), or emotions, will hinder the emotions of the person you are about to interact within and outside the RIPLRT. Also, when addressing conflicts deliver the same or higher level of intelligence and respect as we expect to receive when we deliver our science.
- **will peep up with science as much as possible**. Identify venues to keep informed about scientific innovations (i.e. scientific findings, publications, reports, etc.) related to our [Vision and Mission](https://bookdown.org/friveram/labmanualriplrt/vision-mission-and-core-values.html#vision), as well as those related to improving human health. 
- **will employ time management**. Working everyday in the RIPLRT is not necessary -- we just need to get the job done by dedicating the necessary time to complete our tasks.
- **will keep updated his/her availability**. It is important to keep updated our availability as this will help assign tasks by the PI (Dr. Rivera-Mariani) or the Lab Manager. It is expected that each RIPLRT member or intern will list his/her availability at least 2 weeks in advance, and update the availability as needed. Refer to the platform *WhenIWork*, which is found in section *4.13* this Lab Manual.
- **will provide schedules from other jobs or school (if applicable)**. If any RIPLRT member has other jobs (pair or as volunteer) or academic schedules, he/she will share with the PI a copy of the shift or academic schedule. This facilitates communication between the PI and the RIPLRT members (e.g. sending messages outside of work/class hours) and aligns with our transparency philosophy. 
- **will attend lab meeting and meet deadlines**. Lab members will be grateful when we respect their time: we want them to respect ours. 
- **will do a quick check before leaving the lab**. Make sure our working spaces are clean and organized, and that lab equipment (except the freezer, fridge, and computers) are turned off. Although the computer should not be turned off (unless otherwise stated by the PI or the Lab Manager), it should be on sleep mode. RIPLRT personnel assigned during a particular day in which this expectation is not followed upon, will be accountable and *result 50% waged reduction during that day (if the RIPLRT is on waged-scales).*
- **will know what can and cannot be shared**. The RIPLRT research facilities are within a shared research lab. There are things that can be shared, and there are others that cannot. Make sure to recognize which items falls into these two categories. Refer to the RIPLRT list of shareables and non-shareables items and contact the PI or the Lab Manager if any doubts.
- **will perform inventory control before and after experiments**. Every RIPLRT member is required to pre-calculate the specific amount of consumables and reagents before implementing the experiment. At the end of the experiment, the pre-calculated amounts must be validated and adjusted (if needed) based on what was actually consumed. The hard-copy of the lab notebook would be of great help with this expectation. Also make sure to inform the corresponding RIPLRT members with the task of keeping updated our cloud-platform (Quartzy) for inventory (refer to section *4.8* of this lab manuals) .
- **will report the inventory control in the corresponding platform**. The consumed amounts must be reported in the corresponding Electronic Lab Notebook platform: eLabJournal for waged-members, and RSpace for graduate students and interns unless otherwise stated by the PI of the RIPLRT. Refer to chapter 2 to see into which category you are listed. If from the pre-calculation there are not enough consumables or reagents for a given experiment, the experiment cannot be launched. This would need to be communicated immediately to either the PI or the Lab Manager. At the end of the experiment, the amounts in our inventory platform, Quartzy (see section *4.8*) and eLabJournal (in the case of antibodies and proteins; see section 4.1) needs to be updated. *Note that audits are performed at random, and this is one of the areas evaluated*. 
- **will work honestly**. Never plagiarize work, tamper with data, or omit anything. A “bad” result is still a result; negative results also have the potential to tell us the story behind the experiments, studies, and projects we are involved. It is worth clarifying that analyzing a publicly-available dataset is not plagiarism. In fact, re-analyzing publicly-available datasets is one of the outcomes of the open-science movement, which seeks to address reproducibility in science.*

**For waged RIPLRT members:**
If there are no circumstances preventing a RIPLRT member from completing a task, and the task is not completed, it  could result in the role be converted from Waged (W) to Non-Waged (NW). Also, RIPLRT members' role will start as NW for laboratory techniques and experiments that deliver results and in which precision and accuracy are measurable. If the precision/accuracy is above 95%, the RIPLRT member's role will convert from NW to W. If the experiment needs to be repeated, the RIPLRT member will remain in NW status -- the W hours will correspond only to the instance in which the 95% or above precision/accuracy is accomplished.

Now that we have elaborated on general expectations and guidelines, this seems an appropriate time to mention that most of these expectations stem from the [Aly Lab Manual](https://github.com/alylab/labmanual)(1).  

## Principal Investigator
All general expectations and responsibilities and 

- Be the foundation and example for the lab members to follow
- Be a mentor with many aspects within RIPLRT, including science, learning, personally, emotionally, professionally, with career goals, among others. 
- As much as possible, provide feedback in a timely manner, in all scientific aspects of RIPLRT
- Facilitates as many scientific and learning opportunities as possibel for lab members to benefit from 
- Find and apply for funding, and identify collaborative opportunities 
- Have our backs as long as we have implemented the guidelines and expectations listed in this Lab Manual. Also, be as impartial as possible in this manner. 
- In order to back up us, the Principal Investigator will perform corresponding monthly audits (or as needed) for each platform employed by the RIPLRT
- Will be the chair of the lab meetings unless otherwise stated

## Lab Manager
All general expectations and responsibilities and

- Assist the Principal Investigator in the management of the RIPLRT
- Assist the Principal investigator in overseeing tasks to be completed and implementing Wage-to-Non-Wage status changes (and vice versa) 
- Assist in the ordering of equipment, reagents, and lab consumables
- Manage, develop, and implement strategies for inventory control
- Assist in the preparation of agendas for the bi-weekly and extraordinary meeting
- Serve as mentor for research assistants, graduate and undergraduate students, or other interns
- Elaborate questions that the group can use to develop new research ideas
- Assist in any projects in which mentees may need help with, as well as with the Principal Investigator
- Participate, as much as possible, in professional development opportunities including those identified by the Principal Investigator 
- Be willing to improve written and verbal communication as it pertains to the scientific community as well as communicating science to non-science audiences. 
- Perform other Lab duties as assigned by the PI

## Group Leaders 

- In the event a waged-RIPLRT, or senior RIPLRT, members are not among the current RIPLRT group, group leaders will be selected by and among the RIPLRT members. The Group Leader(s) will assume the responsibilities of a Lab Manager.

## Research Assistants
All general expectations and responsibilities and, 

- Serve as mentors for graduate and undergraduate students, or other interns
- Train lesser experienced lab members, which may include students (graduate and undergraduate), interns, and even research assistants who recently joined the RIPLRT, on lab techniques and protocols, including guidelines and expectations of this lab manual. Refer to section 2.8 for further information about mentors
- Elaborate questions that the group can use to develop new research ideas
- Assist in any projects in which mentees and mentors may need help with, as well as with the Principal Investigator
- Participate, as much as possible, in professional development opportunities including those identified by the Principal Investigator 
- Be willing to improve written and verbal communication as it pertains to the scientific community as well as communicating science to non-science audiences. 
- Perform other Lab duties as assigned by the PI, Lab Manager

**Note**:
- Graduate Research Assistant will assume the role of Research Assistants if waged-RAs are not part of the current RIPLRT group
- these guidelines also apply to **Remote Research Assistants**

## Remote Research Assistants
All general expectations and responsibilities and,

- The guidelines listed for Research Assistants
- Be up-to-date with ongoing projects in the RIPLRT
- Be active, as assigned by the PI and Lab Manager, in revising documents and platforms

## Graduate Students
All general expectations and responsibilities and, 

- Be mentees of research assistants 
- Mentor lesser experiences lab members, which may include undergraduate and graduate students who recently joined the RIPLRT. Refer to section 2.8 for further information about mentors. 
- Learn new skills and procedures ina timely-manner
- Elaborate questions that the group can use to develop new research ideas
- Assist in any projects in which mentees and mentors may need help with, as well as with the Principal Investigator or Lab Manager
- Participate, as much as possible, in professional development opportunities including those identified by the Principal Investigator as well as those identified by yourself
- Be willing to improve written and verbal communication as it pertains to the scientific community as well as communicating science to non-science audiences

## Undergraduate interns
All general expectations and responsibilities and 

- Be mentees of research assistants and graduate students. Refer to sectin 2.8 for further information about mentors and mentees. 
- Learn new skills and procedures quickly
- Assist in any projects in which mentors may need help with, as well as with the Principal Investigator or Lab Manager
- Participate, as much as possible, in professional development opportunities including those identified by the Principal Investigator
- Be willing to improve written and verbal communication as it pertains to the scientific community as well as communicating science to non-science audiences

## Mentors and Mentees
As mentioned above under the research assistants and graduate students expectations, mentoring is an integral component of the listed expectations. Establishing good mentor-mentee relationships is very important. It is highly encourage that mentors and mentees read reference about mentoring before engaging in such relationships. Also, mentors will be expected to be the first in line of ensuring that the mentee abide by the guidelines and expectations in this lab manual. Thus, the initial accountability will fall on the mentors if mentees are not abiding by the expectations and guidelines in this lab manual. 

## Other Expectations
- **Every member must pass a training in Human Subjects Research**. Everyone in the RIPLRT must pass, and maintain, updated certifications performing research with human subjects. Refer to *section 3.5 (Scientific Integrity)* of this lab manual for further information about this certifications.
- **Every lab member must be up-to-date with vaccinations, including against Hepatitis B**. Because human blood is one of the main human body fluids with which the RIPLRT performs research, Hepatitis B vaccination is required. Vaccination records are required to be submitted to the Principle Investigator of the RIPLRT (Dr. Rivera-Mariani).