# Lab Resources

The RIPLRT employs a series of digital resources, which helps many of which helps us protect the environment by being *paperless*, promoting the mission of the RIPLRT, and facilitate our productivity, reproducibility, and to contribute to the [Open-Science movement](http://www.unesco.org/new/en/communication-and-information/portals-and-platforms/goap/open-science-movement/). 

## FigShare and Zenodo:
FigShare^TM^ (https://figshare.com/) and Zenodo^TM^ (https://zenodo.org/) are two of the platforms we employ to contribute to the Open Science movement and the efforts to make reproducible science available to the public, including the scientific community. Make sure to create an account and ask Dr. Rivera-Mariani to invite you into the RIPLRT workspaces within these platforms. Before submitting anything to FigShare or Zenodo and making it public, make sure to consult with Dr. Rivera-Mariani or the Research Assistants. 

## GitHub:
GitHub is a way to share codes (also data) to people outside of our lab. Coding is used throughout our research projects, everyday analysis and website. Our github repository is https://www..github.com/riplrt. Github is one of our venues to contribute to the Open-Science movement (refer to our Wiki page: https://wiki.riplrt.com). Also, make sure to familiarize with Github and to as Dr. Rivera-Mariani or any of the Research Assistant to provide you with a brief training of how to use Github. Before submitting anything to Github and making it public, make sure to consult with Dr. Rivera-Mariani or the Research Assistants. 

## Google account:
**Gmail**: We have a riplrt email domain: username@riplrt.com. All emails should be communicated through this email domain. Make sure to ask Dr. Rivera-Mariani to add you to our domain. **Google drive**: there is a riplrt drive (https://drive.riplrt.com) that will contain all documents shared intra-lab only, including collaborations. **Google calendar**: invites to events and meetings are sent through calendar  

## GoToMeeting: 
Our group meets via GoToMeeting every Monday at 10AM (EST). Some members are not stationed locally and others opt to work from home and this is usually our mode of communication. Make sure to familiarize with this app.

## Homebase
In order to keep track of the hours worked in the lab, we implement the [Homebase](https://joinhomebase.com/) platform for signing in and out. Homebase allows Dr. Rivera-Mariani Rivera to create a schedule on the master account with tasks, shifts, and time slots for RIPLRT members. Another important feature is the desktop sign in sheet that lab members can access on RIPLRT’s computer. Now lets say that the computer is unaccessible, you have to option of signing in on your smartphone that will track your sign in and out location via GPS.
To get started, be sure to let Dr. Rivera-Mariani know and he will send an invite where you will be directed to create an account and start tracking your time in lab. The smartphone app has many features and should can be very useful. If you have any trouble accessing or correctly logging your time sheet please contact Dr. Rivera-Mariani.

## Open Science Framework
Together with Github, FigShare, and Zenogo, we contribute to the Open-Science movement through the Open Science Framework (OSF) platform (https://osf.io/). When data or codes that we have developed and employed in our projects are finally curated (i.e. not needed any other editing), they will be uploaded to the OSF. As with GitHub, FigShare, and Zenodo, consult with Dr. Rivera-Mariani or the Research Assistants before submitting anything to OSF and making it public.

## PubCrawler: 
Keeping up with science, including in topics related to the RIPLRT scientific mission, sometimes is challenging. We use PubCrawler (http://pubcrawler.gen.tcd.ie/) to help narrow the difficulties of being up-to-date with scientific findings. Make sure to create an account with PubCrawler and review the weekly hits PubCrawler will send you as they relate to topic of the RIPLRT’s research mission.  Make sure to familiarize with this  plateform.

## R and R Studio
Our lab also employs reproducible approaches for analyzing data. For this purpose, our data analysis protocols use [R](https://www.r-project.org/) and [Rstudio](https://www.rstudio.com/) as the platforms. Here we employ scripts that we often share through Github, RSpace, Open Science Framework, FigShare, and Zenodo. Learning to use R and Rstudio will be one of the skillsets you will develop with the RIPLRT.

## Rspace: 
Our lab uses Rspace (https://community.researchspace.com/login) for our electronic lab records. Each member who has worked in the lab is required to write up the lab in their assigned, hard copy notebook then document again on Rspace.

## Slack: 
Our principal venue of communication (daily and in weekends) is through Slack^TM^. Our work space is riplrt.slack.com. We have seperate channels with different themes about ongoing topics in the lab. We are able to share information, documents, and pictures through Slack^TM^. Make sure to ask Dr. Rivera-Mariani to add you into our Slack workspace, and to familiarize with this app. 

## Website: 
The RIPLRT has a motherboard known as our website (www.riplrt.com). Here you will find oodles of past, current, and future information regarding the group. You can also follow RIPLRT’s updates and blogs here. Similar to this lab  manual, it is also a work-in-progress. Each lab member must provide a profile photo and a short bio to be included in the lab members section (https://www.riplrt.com/members/).

## Wiki:
The RIPLRT lab has a wiki page (http://wiki.riplrt.com/), where we share the library of resources and information we employ in our daily endeavors in the RIPLRT. You will be amazed all the resources we integrate in our scientific-mentoring mission. Similar to this lab manual, our Wiki page is also a work-in-progress.



